### ISSUE TITLE
Support to Sunmi T2

### ISSUE THREAD

**Issue by ldtung** [mitsuharu/react-native-sunmi-printer-library#29]
**Is your feature request related to a problem? Please describe.**
Currently, when using this library, i can print for V1 and V2 Sunmi devices but for T2, the speed for printing is slow. Furthermore, the bold style is not working for T2 but ok for V1 and V2

**Describe the solution you'd like**
Support for Sunmi T2

**Describe alternatives you've considered**
Probably Sunmi T2 has another SDK?

**Additional context**
None

**Comment by ldtung** [comment]
https://github.com/mitsuharu/react-native-sunmi-printer-library/assets/14136312/f6c0023a-b363-4829-9116-a191e04a63ea

You can look at this video for the current issue

**Comment by mitsuharu** [comment]
I do not have SUNMI T2, so that do not plan to support it. Sorry.

I thought ways to fix it as follows.
If not, please you contact Sunmi support  for Android Sunmi inner printer library and SUNMI T2.

1. SDK

SUNMI Developer writes that it works with same SDK, not need another SDK.
https://developer.sunmi.com/docs/en-US/ceghjk502/craeghjk480

My library uses version 1.0.22.
You try using [patch-package](https://www.npmjs.com/package/patch-package) to upgrade or downgrade version.

```gradle
implementation "com.sunmi:printerlibrary:1.0.22"
```

https://github.com/mitsuharu/react-native-sunmi-printer-library/blob/main/android/build.gradle#L101

2. printing is slow

Do you try Transaction? It uses PrintText without await.

```typescript
await SunmiPrinterLibrary.enterPrinterBuffer(true)

SunmiPrinterLibrary.printText('Transaction Test 1')
SunmiPrinterLibrary.printText('Transaction Test 2')
SunmiPrinterLibrary.printText('Transaction Test 3')

await SunmiPrinterLibrary.exitPrinterBuffer(true)
```

3. bold style is not working

Try the ESC/POS command directly with sendRAWData.

```typescript
import { Buffer } from 'buffer'

const boldOn = new Uint8Array([0x1B, 0x45, 0x01])
const boldOnBase64 = Buffer.from(boldOn).toString('base64')
await SunmiPrinterLibrary.sendRAWData(boldOnBase64)

await SunmiPrinterLibrary.printText('Bold is ON')

const boldOff = new Uint8Array([0x1B, 0x45, 0x00])
const boldOffBase64= Buffer.from(boldOff).toString('base64')
await SunmiPrinterLibrary.sendRAWData(boldOffBase64)

await SunmiPrinterLibrary.printText('Bold is OFF')
```

**Comment by ldtung** [comment]
OK thanks, let me try it out
